name: 🐍 Auto Version Tag

on:
  push:
    branches:
      - main
    paths:
      - 'my_python_template/__init__.py'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Version tag
        uses: Jorricks/action-python-autotagging@1.0.1

        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: my_python_template/__init__.py
          variable: __version__